version: '3.9'

name: thanarak-server

services:
  nginx:
    build: ./nginx
    ports:
      - '80:80'
    networks:
      - client_frontend
      - server_backend

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - strapi:/var/lib/postgresql/data
    networks:
      - server_backend

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8081:8080
    networks:
      - server_backend

volumes:
  strapi:

networks:
  client_frontend:
    name: 'client_frontend'
    external: true
  server_backend:
    name: 'server_backend'
