version: "3.9"

name: thanarak-strapi

services:
  strapi:
    build:
      context: ../../
      dockerfile: ./.docker/production/Dockerfile
    image: thanarack-strapi-env-production
    networks:
      - server_backend
      - client_frontend

networks:
  client_frontend:
    name: "client_frontend"
    external: true
  server_backend:
    name: "server_backend"
    external: true
